# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.5
    parallelism: 3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      # Step 2: create virtual env and install dependencies
      - run:
          name: Install Dependencies
          command: |
            pipenv install

      # Step 3: run linter
      - run:
          name: Run Linter
          command: |
            pipenv run flake8

      # Step 4: run tests and coverage
      - run:
          name: Run Tests and Coverage
          command: |
            pipenv run coverage run --source='.' --omit="*/asgi.py,*/wsgi.py,*/manage.py,*/config/settings.py" ./manage.py test
            pipenv run coverage report

workflows:
  version: 2
  build_then_deploy:
    jobs:
      - build_and_test
